# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b84e2e6a637de17369eeb3011d5084a5577db591cc2404594d69d090dffc8b267db7dd7b6e3258261a06ff12b870742bb8086d3b10db5f8d0a0a452a696163cb

test:
  secret_key_base: 628871b89ead15eab3cfcdce2307bb9d4caa11b0f9ff65661f587cc8d7a0ed226b51ce50793a88cd02a84ee87c7aa480170a838e4cf05af93980a85a7ba19795

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
